apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: loki-datasource
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_datasource: "1"

resources:
  - helm-release.yaml
