apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-stack
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "11.3.4"
  interval: 1h0m0s
  dependsOn: 
    - name: flux-system
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: hrv-prometheus-stack