apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: hrv-prometheus-stack
    files:
      - values.yaml

resources:
  - helm-release.yaml
